# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 668)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnBlendImages = QtWidgets.QPushButton(self.centralwidget)
        self.btnBlendImages.setGeometry(QtCore.QRect(350, 610, 92, 27))
        self.btnBlendImages.setObjectName("btnBlendImages")
        self.StartingImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.StartingImage.setGeometry(QtCore.QRect(20, 40, 321, 231))
        self.StartingImage.setObjectName("StartingImage")
        self.btnLoadStartingImage = QtWidgets.QToolButton(self.centralwidget)
        self.btnLoadStartingImage.setGeometry(QtCore.QRect(20, 10, 171, 25))
        self.btnLoadStartingImage.setObjectName("btnLoadStartingImage")
        self.btnLoadEndingImage = QtWidgets.QToolButton(self.centralwidget)
        self.btnLoadEndingImage.setGeometry(QtCore.QRect(490, 10, 161, 25))
        self.btnLoadEndingImage.setObjectName("btnLoadEndingImage")
        self.chkShowTriangles = QtWidgets.QCheckBox(self.centralwidget)
        self.chkShowTriangles.setGeometry(QtCore.QRect(340, 280, 131, 22))
        self.chkShowTriangles.setAutoFillBackground(False)
        self.chkShowTriangles.setCheckable(True)
        self.chkShowTriangles.setObjectName("chkShowTriangles")
        self.sliderAlpha = QtWidgets.QSlider(self.centralwidget)
        self.sliderAlpha.setGeometry(QtCore.QRect(130, 310, 531, 20))
        self.sliderAlpha.setAutoFillBackground(False)
        self.sliderAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAlpha.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderAlpha.setTickInterval(10)
        self.sliderAlpha.setObjectName("sliderAlpha")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 310, 62, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 280, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 280, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 590, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtAlphaValue = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAlphaValue.setGeometry(QtCore.QRect(670, 306, 51, 31))
        self.txtAlphaValue.setText("")
        self.txtAlphaValue.setObjectName("txtAlphaValue")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 340, 62, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(640, 340, 62, 17))
        self.label_6.setObjectName("label_6")
        self.EndingImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.EndingImage.setGeometry(QtCore.QRect(470, 40, 321, 231))
        self.EndingImage.setObjectName("EndingImage")
        self.BlendingResult = QtWidgets.QGraphicsView(self.centralwidget)
        self.BlendingResult.setGeometry(QtCore.QRect(230, 340, 341, 241))
        self.BlendingResult.setObjectName("BlendingResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBlendImages.setText(_translate("MainWindow", "Blend"))
        self.btnLoadStartingImage.setText(_translate("MainWindow", "Load Starting Image ..."))
        self.btnLoadEndingImage.setText(_translate("MainWindow", "Load Ending Image ..."))
        self.chkShowTriangles.setText(_translate("MainWindow", "Show Triangles"))
        self.label.setText(_translate("MainWindow", "Alpha"))
        self.label_2.setText(_translate("MainWindow", "Starting Image"))
        self.label_3.setText(_translate("MainWindow", "Ending Image"))
        self.label_4.setText(_translate("MainWindow", "Blending Result"))
        self.label_5.setText(_translate("MainWindow", "0.0"))
        self.label_6.setText(_translate("MainWindow", "1.0"))

